/**
 * Seed data for the pipeline store — the real trial client.
 *
 * Loaded once by src/lib/pipelineStore.js when .data/pipeline.json does not
 * exist yet. Everything here follows the compliance rails in docs/BRAND.md:
 * program facts cite the program, never "you"; no odds, approvals, or
 * outcomes are stated or implied; unverified items are labeled as such.
 *
 * Opportunities below are the VERIFIED research fleet deliverable
 * (2026-08-20): 57 programs researched, 38 screened, top 8 re-verified
 * against primary sources. Deadlines must be re-verified before any
 * submission. See docs/trial-run/HIFR-opportunity-sheet.md.
 */

export function buildSeedState() {
  const at = new Date().toISOString();

  const client = {
    id: "client-hitf-restoration",
    name: "Home Is the Foundation Restoration",
    location:
      "West Liberty, Morgan County, Eastern Kentucky (ARC-designated Appalachian county)",
    entityType: "508(c)(1)(A) faith-based organization (no IRS determination letter)",
    missionSummary:
      "Critical home repair for elderly and low-income homeowners — the \"dry-in\" scope: " +
      "roof leak repair, subfloor and structural repair, accessibility ramps, and " +
      "underpinning/winterization. Materials come partly from a reclaimed-materials " +
      "supply chain (barn deconstruction, scratch-and-dent rescue). Labor model is " +
      "volunteer crews plus homeowner sweat equity, with trades mentorship for " +
      "local workers. Startup organization; plans to stand up a separate 501(c)(3) " +
      "community development corporation (CDC) in the future.",
    contacts: [],
    createdAt: at,
    status: "active",
    notes: [
      {
        at,
        text:
          "KEY ELIGIBILITY CONSTRAINT — no IRS determination letter. The organization " +
          "operates as a 508(c)(1)(A) faith-based entity, which claims tax-exempt " +
          "status automatically rather than through an IRS 501(c)(3) determination " +
          "letter. Many funders ask for that letter as proof of exempt status. Each " +
          "opportunity must be checked for whether the program accepts a 508(c)(1)(A) " +
          "without a letter, allows a fiscal sponsor, or requires the letter outright. " +
          "Track this per-opportunity in the requires501c3Letter field.",
      },
      {
        at,
        text:
          "Startup with no grant history and no prior awards. First applications will " +
          "need extra lead time for organizational documents (budget, board list, " +
          "financial statements or a statement that none exist yet).",
      },
      {
        at,
        text:
          "Plans a future 501(c)(3) CDC. If formed, that entity could hold a " +
          "determination letter and may widen which programs the organization can " +
          "apply to — revisit parked opportunities if that happens.",
      },
      {
        at,
        text:
          "Location context: Morgan County, KY is an ARC-designated Appalachian " +
          "county. Several rural and Appalachian programs cite county designation in " +
          "their published eligibility criteria — verify current designation status " +
          "during vetting for each opportunity.",
      },
    ],
  };

  const opportunities = [
    {
      id: "opp-usda-hpg-533",
      clientId: client.id,
      name: "USDA Housing Preservation Grants (Section 533) \u2014 FY2026 partner ask / FY2027 direct",
      funder: "USDA Rural Development",
      funderType: "federal",
      awardBand: "Org-facing program; repair scopes commonly $5k\u2013$25k+ per home under grantee programs",
      fitRationale: "The program's published purpose funds organizations repairing housing occupied by low- and very-low-income rural residents \u2014 directly aligned with the dry-in scope. FY2026 direct application unrealistic (no SAM.gov, no track record); the near-term play is being named construction/volunteer partner in an established applicant's FY2026 submission.",
      eligibilityNotes: "Regulation requires nonprofit incorporation; whether a determination letter is expressly required is an open question for the KY RD State Office. Partner route via Frontier Housing or Gateway CAA needs no letter. Start SAM.gov/UEI registration regardless.",
      requires501c3Letter: "unclear",
      cadenceOrDeadline: "FY2026 NOFA closes Sep 8, 2026 (partner ask only); FY2027 cycle for a direct/consortium application",
      sources: ["https://www.rd.usda.gov/programs-services/single-family-housing-programs/housing-preservation-grants"],
      status: "go_decision",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "go_decision", at, note: "Time-critical: partner ask must go to Frontier Housing / Gateway CAA before the Sep 8, 2026 close." }],
      nextAction: "Go/no-go this week: call Frontier (606-784-2131) and Gateway (606-743-3133) asking to be named construction/volunteer partner in their FY2026 HPG application; ask KY RD whether incorporation without a letter suffices for FY2027.",
    },
    {
      id: "opp-arc-area-development",
      clientId: client.id,
      name: "ARC Area Development grant via Morgan County Fiscal Court / Gateway ADD",
      funder: "Appalachian Regional Commission via KY Dept for Local Government",
      funderType: "federal-state partnership",
      awardBand: "80% federal share available in ARC-distressed counties; project-sized awards",
      fitRationale: "Morgan County is ARC-distressed, which raises the federal share. The county fiscal court or Gateway Area Development District applies; the organization serves as implementing partner \u2014 the youth trades-training component fits ARC workforce priorities.",
      eligibilityNotes: "County government is the applicant, so the organization's tax status is not the gate. The ask is a concept call with DLG ARC staff and Gateway ADD.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "FY27 window open to Sep 30, 2026",
      sources: ["https://www.arc.gov/funding-opportunities/"],
      status: "go_decision",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "go_decision", at, note: "Time-critical: county-partner concept call needed before the Sep 30, 2026 window close." }],
      nextAction: "Request a meeting with the Morgan County Judge/Executive and Gateway ADD community development staff about carrying an FY27 application with the organization as implementing partner.",
    },
    {
      id: "opp-walmart-spark-good",
      clientId: client.id,
      name: "Walmart Spark Good Local Grants",
      funder: "Walmart / Sam's Club (Walmart.org)",
      funderType: "corporate",
      awardBand: "$250\u2013$5,000 per grant",
      fitRationale: "Walmart's published guidelines include a faith-based/church eligibility track separate from 501(c)(3) \u2014 one of the few corporate cash grants plausibly open as-is. Verified open cycle; best odds of a first cash grant this fall.",
      eligibilityNotes: "Deed verification may stall on an organization absent from the IRS Business Master File \u2014 start verification early; fallback is applying through a verified partner church.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Cycle open Aug 1 \u2013 Nov 30, 2026 (verified)",
      sources: ["https://www.walmart.org/how-we-give/program-guidelines/spark-good-local-grants-guidelines"],
      status: "go_decision",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "go_decision", at, note: "Open now; Deed verification lead time makes this a start-this-week item." }],
      nextAction: "Create the Spark Good account and begin Deed verification with EIN and organizing documents; if verification stalls, pivot to a verified partner church as applicant.",
    },
    {
      id: "opp-berea-appalachian-fund",
      clientId: client.id,
      name: "Berea College Appalachian Fund (via fiscal sponsor)",
      funder: "Berea College",
      funderType: "foundation",
      awardBand: "Program grants; regional Appalachian fund",
      fitRationale: "Nearest live foundation deadline in the region and a strong mission fit (Appalachian community wellbeing). Only reachable this cycle through a 501(c)(3) fiscal sponsor \u2014 which makes it the forcing function for the sponsorship decision.",
      eligibilityNotes: "Requires 501(c)(3); sponsor route must be confirmed by phone (859-985-3635) and a sponsor signed within ~6 weeks. Frontier Housing is the natural candidate.",
      requires501c3Letter: "yes",
      cadenceOrDeadline: "Inquiry due Oct 10, 2026; full application Oct 19, 2026",
      sources: ["https://www.berea.edu/"],
      status: "go_decision",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "go_decision", at, note: "Sponsor-dependent: only viable if a fiscal sponsor signs in the next ~6 weeks \u2014 go/no-go now." }],
      nextAction: "Call Berea to confirm sponsored applications are accepted; pair with the Frontier fiscal-sponsorship ask already in motion.",
    },
    {
      id: "opp-gateway-wap-liheap",
      clientId: client.id,
      name: "Gateway CAA \u2014 WAP deferral-repair partnership + LIHEAP shepherding",
      funder: "Gateway Community Action (West Liberty) / DOE WAP / LIHEAP",
      funderType: "federal via community action agency",
      awardBand: "Federal weatherization dollars stacked per home on the organization's volunteer labor",
      fitRationale: "Weatherization crews must defer homes with roof leaks or structural problems \u2014 exactly the dry-in niche. A deferral-referral pilot unblocks Gateway's deferred homes and gives the organization documented track record with a federal program partner headquartered in West Liberty. Verified: Gateway serves Morgan County; LIHEAP Summer Cooling open through Sep 11, 2026.",
      eligibilityNotes: "No eligibility gate \u2014 this is an operating partnership, not a grant application.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Rolling partnership; LIHEAP Summer Cooling closes Sep 11, 2026",
      sources: ["https://gatewaycaa.org/csbg-liheap-locations/", "https://www.capky.org/home-page/kentucky-liheap-summer-subsidy-cooling-component-august-3-september-11-2026/"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Verified against Gateway and CAPKY pages; engagement call is the next step (confirm street address when scheduling \u2014 two are published)." }],
      nextAction: "Call 606-743-3133; propose the deferral-referral pilot and ask how many Morgan County homes sit on the WAP deferral list.",
    },
    {
      id: "opp-usda-504",
      clientId: client.id,
      name: "USDA Section 504 Home Repair \u2014 homeowner shepherding",
      funder: "USDA Rural Development",
      funderType: "federal (homeowner-direct)",
      awardBand: "Per home: $10,000 lifetime grant (homeowners 62+), $40,000 1%/20-yr loan, $50,000 combined (standard caps, verified)",
      fitRationale: "Rolling, year-round, all of Morgan County eligible. The homeowner applies, so the organization's status is irrelevant \u2014 its role is screening, file packaging, and pairing 504 dollars with sweat-equity labor, which multiplies both.",
      eligibilityNotes: "No organizational gate. Program live in FY2026 (verified: $25M loans / $21M grants allocated).",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Rolling \u2014 applications accepted year-round",
      sources: ["https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-repair-loans-grants"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Verified against USDA RD pages; ready for homeowner file starts." }],
      nextAction: "Call the KY RD area office for the packaging checklist and Morgan County very-low-income limits; open 3\u20135 elderly-homeowner files.",
    },
    {
      id: "opp-frontier-housing",
      clientId: client.id,
      name: "Frontier Housing \u2014 referral MOU / subcontract / candidate fiscal sponsor",
      funder: "Frontier Housing (Morehead, KY)",
      funderType: "regional housing nonprofit",
      awardBand: "Funded repair scopes commonly $5k\u2013$25k+ per referred home under Frontier's programs",
      fitRationale: "The established repair organization already covering Morgan County (verified 22-county service area; roofing, ramps, accessibility scopes) and the credibility bridge to Fahe, KHC, and USDA HPG. Also the natural fiscal-sponsor candidate, which would unlock the foundation tier.",
      eligibilityNotes: "Partnership requires no letter. Fiscal-sponsor willingness is an ask, not a fact \u2014 frame it that way. A repair-jobs bidding figure from research notes could not be publicly verified; treat as a question to ask.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Rolling relationship; sponsor decision needed within ~6 weeks to reach the Oct 10 Berea inquiry",
      sources: ["https://frontierky.org/what-we-do/"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Verified service area and scopes; the capability-statement call is next." }],
      nextAction: "Call 606-784-2131 with a one-page capability statement; ask about a referral MOU, repair subcontracting, and fiscal sponsorship.",
    },
    {
      id: "opp-thrivent-action-teams",
      clientId: client.id,
      name: "Thrivent Action Teams",
      funder: "Thrivent (fraternal benefit society)",
      funderType: "fraternal micro-grant",
      awardBand: "$250 seed money per team; full benefit members may lead up to 2 teams/year (associate members 1)",
      fitRationale: "No nonprofit status of any kind required \u2014 verified on Thrivent's pages. $250 plus organized volunteers equals one ramp or one roof patch; several members across partner churches compounds it.",
      eligibilityNotes: "No gate. The constraint is finding Thrivent members in the church network.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Rolling",
      sources: ["https://www.thrivent.com/about-us/membership/thrivent-action-teams"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Verified; recruiting members is the only step." }],
      nextAction: "Canvass partner churches for Thrivent members; schedule the first Action Team against the top intake case.",
    },
    {
      id: "opp-mountain-association",
      clientId: client.id,
      name: "Mountain Association \u2014 Business Support (capacity consulting)",
      funder: "Mountain Association (Berea, KY)",
      funderType: "regional CDFI / capacity builder",
      awardBand: "Consulting engagements paid up to 100% by Mountain Association; CDFI loans from $1,000 if needed",
      fitRationale: "Serves all 54 Appalachian Kentucky counties including Morgan. Free consulting (bookkeeping, financial systems, planning) directly fixes the no-staff/no-systems weakness that drags every other application in this list.",
      eligibilityNotes: "Nonprofits explicitly eligible for Business Support; no tax-status gate found. Confirm 508(c)(1)(A) treatment with the lending team if a loan is ever wanted.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Rolling",
      sources: ["https://mtassociation.org/business-support/"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Verified; inquiry submission is next." }],
      nextAction: "Submit a Business Support inquiry for startup financial systems and a fundraising-ready plan.",
    },
    {
      id: "opp-cap-operation-sharing",
      clientId: client.id,
      name: "Christian Appalachian Project \u2014 Operation Sharing (materials)",
      funder: "Christian Appalachian Project (Paintsville, KY)",
      funderType: "faith-based materials pipeline",
      awardBand: "Free donated goods including building supplies (200+ truckloads distributed since July 2022)",
      fitRationale: "Partner network of ~1,500 organizations including churches, about an hour from West Liberty \u2014 extends the reclaimed-materials supply chain. Important fence (verified): CAP's Home Repair program does NOT serve Morgan County; this is materials only.",
      eligibilityNotes: "Church-status organizations plausibly qualify; documentation requirements unconfirmed \u2014 ask. Fallback is partnering through a sponsoring congregation.",
      requires501c3Letter: "unclear",
      cadenceOrDeadline: "Rolling",
      sources: ["https://www.christianapp.org/operation-sharing"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Verified program and county fence; partner-requirements call is next." }],
      nextAction: "Call 866-270-4227 and ask partner requirements for a church-status organization.",
    },
    {
      id: "opp-pcusa-sdop",
      clientId: client.id,
      name: "PC(USA) Self-Development of People (SDOP) national grant",
      funder: "Presbyterian Church (U.S.A.)",
      funderType: "denominational",
      awardBand: "Up to $15,000",
      fitRationale: "Rare national grant gated on beneficiary ownership and control rather than IRS status. The mutual-aid, sweat-equity model genuinely fits if bylaws put homeowner-members in governance \u2014 a structural change worth making on its own merits.",
      eligibilityNotes: "No IRS-status gate; criteria are community ownership/control. Requires governance where beneficiaries hold decision-making power, plus recommendation letters.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Rolling; roughly six-month review cycle",
      sources: ["https://www.presbyterianmission.org/ministries/sdop/"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Screened and shortlisted; governance review is the gating step." }],
      nextAction: "Review bylaws for beneficiary-majority governance; submit the pre-application; line up three recommendation letters.",
    },
    {
      id: "opp-homeowner-direct-cluster",
      clientId: client.id,
      name: "Homeowner-direct cluster: VA HISA + Gateway AAA Homecare + LIHEAP screens",
      funder: "VA / Gateway Area Agency on Aging / KY LIHEAP",
      funderType: "homeowner-direct programs",
      awardBand: "VA HISA $2,000\u2013$6,800 per eligible veteran; AAA Homecare minor repairs/mods for 60+; LIHEAP utility assistance",
      fitRationale: "Zero organizational barrier \u2014 these ride on intake screening. Adding veteran-status and ADL screens to the intake form routes each family to every dollar they can already access, stacked with the organization's labor.",
      eligibilityNotes: "No gate; the organization shepherds applications.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Rolling (HISA); AAA per assessment; LIHEAP per season",
      sources: ["https://www.prosthetics.va.gov/psas/HISA2.asp"],
      status: "vetting",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "vetting", at, note: "Verified; intake-form update and two relationship meetings are next." }],
      nextAction: "Add veteran and ADL screens to intake; meet the county VSO and Gateway AAA staff in Morehead.",
    },
    {
      id: "opp-ky-umc-ekm",
      clientId: client.id,
      name: "KY United Methodist \u2014 Eastern Kentucky Ministries grants",
      funder: "Kentucky Annual Conference, UMC",
      funderType: "denominational",
      awardBand: "Small grants (Mission Grants up to $2,000; EKM amounts unpublished)",
      fitRationale: "Housing insecurity is a named category and the application is posted year-round for Eastern Kentucky ministries. Small dollars, low friction, and a denominational relationship that compounds.",
      eligibilityNotes: "Ask directly whether a 508(c)(1)(A) qualifies; courting a local UMC congregation as partner covers the alternative.",
      requires501c3Letter: "unclear",
      cadenceOrDeadline: "Year-round (EKM); Mission Grants on a spring cycle",
      sources: ["https://www.kyumc.org/"],
      status: "identified",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." }],
      nextAction: "Submit the EKM application; ask about 508(c)(1)(A) eligibility; identify a local UMC congregation for the spring Mission Grant cycle.",
    },
    {
      id: "opp-fhlb-peterson",
      clientId: client.id,
      name: "FHLB Cincinnati \u2014 Carol M. Peterson Housing Fund (via member bank)",
      funder: "Federal Home Loan Bank of Cincinnati",
      funderType: "bank consortium fund",
      awardBand: "$5,000\u2013$20,000 per home from a large annual pool",
      fitRationale: "Accessibility and emergency repairs for elderly and disabled homeowners \u2014 squarely the mission. A member bank applies; the 2026 pool was exhausted in roughly 2.5 hours, so pre-packaged homeowner files submitted in the first hour are the whole game.",
      eligibilityNotes: "Route runs through a member bank with Morgan County presence, with Frontier or Gateway as experienced sponsor if the bank wants one. No direct application by the organization.",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Annual opening, ~Feb 2027; funds go in hours",
      sources: ["https://www.fhlbcin.com/"],
      status: "identified",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." }],
      nextAction: "Meet the bank's CRA officer this fall; pre-package 3\u20135 elderly-homeowner files ready to file within the first hour of the opening.",
    },
    {
      id: "opp-fak-civic-experiment",
      clientId: client.id,
      name: "Foundation for Appalachian Kentucky \u2014 Civic Experiment grants",
      funder: "Foundation for Appalachian Kentucky",
      funderType: "regional community foundation",
      awardBand: "$5,000\u2013$20,000",
      fitRationale: "The only regional foundation grant found that is open to informal and non-501(c)(3) groups \u2014 a direct fit for the organization's current status if the 2027 round runs and Morgan County is in scope.",
      eligibilityNotes: "Open to non-501(c)(3) groups per program design; confirm Morgan County eligibility and the 2027 round by phone (606-439-1357).",
      requires501c3Letter: "no",
      cadenceOrDeadline: "Expected ~Jan\u2013Feb 2027 (2027 round unconfirmed)",
      sources: ["https://www.appalachianky.org/"],
      status: "identified",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." }],
      nextAction: "Call to confirm the 2027 round and county eligibility; get on the notification list.",
    },
    {
      id: "opp-arc-flex-e",
      clientId: client.id,
      name: "ARC Flex-E Mini Grants (Center for Rural Development)",
      funder: "ARC via Center for Rural Development",
      funderType: "federal pass-through mini-grant",
      awardBand: "Up to $10,000 with a 20% match",
      fitRationale: "Sized and structured as a winnable first grant for a small organization; volunteer labor may count toward match (confirm). Screen ranked it among the most accessible cash grants on the list.",
      eligibilityNotes: "Ask whether 508(c)(1)(A) documentation is accepted and whether volunteer labor counts as match (arc@centertech.com).",
      requires501c3Letter: "unclear",
      cadenceOrDeadline: "2027 RFP expected in winter",
      sources: ["https://www.centertech.com/"],
      status: "identified",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." }],
      nextAction: "Email the program office with the two eligibility questions and request a sample funded application.",
    },
    {
      id: "opp-aarp-homefit",
      clientId: client.id,
      name: "AARP Community Challenge \u2014 HomeFit microgrant",
      funder: "AARP",
      funderType: "national nonprofit program",
      awardBand: "$2,500 flat",
      fitRationale: "Home-modification microgrants for older adults; the published eligibility includes a case-by-case clause that is a genuine opening for a non-501(c)(3) with a strong, documented elderly-homeowner caseload.",
      eligibilityNotes: "Case-by-case eligibility clause; a county or senior-center support letter strengthens the file.",
      requires501c3Letter: "unclear",
      cadenceOrDeadline: "Opens ~late Jan 2027",
      sources: ["https://www.aarp.org/livable-communities/community-challenge/"],
      status: "identified",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." }],
      nextAction: "Document 5\u201310 elderly-homeowner modification cases with photos and consent; secure a support letter.",
    },
    {
      id: "opp-steele-reese",
      clientId: client.id,
      name: "Steele-Reese Foundation \u2014 Appalachian Kentucky program (sponsor route)",
      funder: "The Steele-Reese Foundation",
      funderType: "private foundation",
      awardBand: "Historically averages around $22,000",
      fitRationale: "Appalachian Kentucky program with education as top priority \u2014 the youth trades-mentorship component is the lead angle. Reachable only through a fiscal sponsor or partner co-applicant.",
      eligibilityNotes: "Requires IRS recognition; call the Appalachian Director before November to confirm sponsored projects are accepted.",
      requires501c3Letter: "yes",
      cadenceOrDeadline: "Deadline Mar 2027; pre-call before November 2026",
      sources: ["https://steele-reese.org/"],
      status: "identified",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." }],
      nextAction: "Confirm sponsored-project acceptability by phone; lead with the youth trades-mentorship framing.",
    },
    {
      id: "opp-hud-oahmp",
      clientId: client.id,
      name: "HUD Older Adults Home Modification Program",
      funder: "HUD",
      funderType: "federal",
      awardBand: "$2M\u2013$3M grants (national program scale)",
      fitRationale: "Long-horizon: requires a 501(c)(3) and three years of documented senior service, at a scale beyond a no-staff startup. The bridge action costs nothing: log every senior served starting now, which starts the three-year clock, and pitch a rural-delivery subcontract to a current grantee this winter.",
      eligibilityNotes: "Parked pending the future 501(c)(3) CDC and a documented service history.",
      requires501c3Letter: "yes",
      cadenceOrDeadline: "Periodic NOFOs; revisit at CDC formation",
      sources: ["https://www.hud.gov/program_offices/housing/sfh/oahmp"],
      status: "parked",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "parked", at, note: "Parked: gated on the future CDC plus a 3-year senior-service history \u2014 start the service log now." }],
      nextAction: "Log every senior served from day one; this winter, pull the current grantee list and pitch a Morgan County rural-delivery subcontract.",
    },
    {
      id: "opp-rebuilding-together",
      clientId: client.id,
      name: "Rebuilding Together affiliation",
      funder: "Rebuilding Together",
      funderType: "national home-repair network",
      awardBand: "Affiliation unlocking national program funds and corporate project dollars",
      fitRationale: "The clearest single argument for obtaining a determination letter: a hard 501(c)(3) requirement guarding the strongest national home-repair affiliation. Queue for the CDC.",
      eligibilityNotes: "Hard 501(c)(3) requirement \u2014 no workaround found.",
      requires501c3Letter: "yes",
      cadenceOrDeadline: "Revisit at CDC formation",
      sources: ["https://rebuildingtogether.org/"],
      status: "parked",
      statusHistory: [{ status: "identified", at, note: "Research fleet: 57 programs researched, 38 screened; this entry from the verified screen (2026-08-20)." },
      { status: "parked", at, note: "Parked: hard 501(c)(3) gate; queued for the future CDC." }],
      nextAction: "Revisit when the CDC's determination letter is in hand.",
    },
  ];

  return {
    version: 1,
    seededAt: at,
    clients: [client],
    opportunities,
  };
}
